### ISSUE TITLE
Spec energy reminder 

### ISSUE THREAD

**Issue by Z7-z** [InfernoStats/death-charge-reminder#1]
The death charge reminder is excellent and is very helpful, used by pretty much everyone, however upon looking through the 482 notification plugins I couldn't actually find any way to remind me when my spec energy is at a certain point. There is 'Idle Notifier' but it just puts a message in the chat, and not only does the chat get flooded with messages but alot of the time I have it closed anyway. An additional reminder popping up for spec energy would be amazing if possible

**Comment by InfernoStats** [comment]
This is a different plugin idea. Feel free to make it.

**Comment by Z7-z** [comment]
> This is a different plugin idea. Feel free to make it.

bro i cant pull plugins out im not that much of a gigachad
