### ISSUE TITLE
Allow overlay duration in seconds

### ISSUE THREAD

**Issue by Z7-z** [InfernoStats/death-charge-reminder#2]
Commonly combined with thrall helper, and that allows for overlay duration in seconds, it would be really nice if we could match these easily instead of having one with a duration in ticks and the other in seconds

**Comment by InfernoStats** [comment]
This isn't a setting people change frequently so can you not just set the one in seconds in terms of game ticks?

i.e. 3 seconds for thrall helper and 5 ticks for death charge reminder

**Comment by InfernoStats** [comment]
The Thrall Helper plugin only runs this once every game tick anyway:

```Java
	@Subscribe
	public void onGameTick(GameTick event)
	{
		if (lastThrallExpiry != null)
		{
			final Duration thrallOverlayTimeout = Duration.ofSeconds(config.thrallTimeoutSeconds());
			final Duration sinceThrallExpiry = Duration.between(lastThrallExpiry, Instant.now());

			if (sinceThrallExpiry.compareTo(thrallOverlayTimeout) >= 0)
			{
				overlayManager.remove(overlay);
				lastThrallExpiry = null;
			}
		}
		if (!(client.getVarbitValue(SPELLBOOK_VARBIT) == ARCEUUS_SPELLBOOK) && config.onlyArceuus()) {
			overlayManager.remove(overlay);
			lastThrallExpiry = null;
		}
	}
```

**Comment by Z7-z** [comment]
> The Thrall Helper plugin only runs this once every game tick anyway:
> 
> ```java
> 	@Subscribe
> 	public void onGameTick(GameTick event)
> 	{
> 		if (lastThrallExpiry != null)
> 		{
> 			final Duration thrallOverlayTimeout = Duration.ofSeconds(config.thrallTimeoutSeconds());
> 			final Duration sinceThrallExpiry = Duration.between(lastThrallExpiry, Instant.now());
> 
> 			if (sinceThrallExpiry.compareTo(thrallOverlayTimeout) >= 0)
> 			{
> 				overlayManager.remove(overlay);
> 				lastThrallExpiry = null;
> 			}
> 		}
> 		if (!(client.getVarbitValue(SPELLBOOK_VARBIT) == ARCEUUS_SPELLBOOK) && config.onlyArceuus()) {
> 			overlayManager.remove(overlay);
> 			lastThrallExpiry = null;
> 		}
> 	}
> ```

infernostats what you have just sent looks like a foreign language to me so I will take your word for it

**Comment by InfernoStats** [comment]
In essence, the thrall helper plugin doesn't actually work in seconds. It works in game ticks so if you set it to disappear after 1 second, it will disappear after 1.2 seconds.
